# Generated by Django 4.2.3 on 2023-07-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_validator', '0004_remove_certificate_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='title',
            new_name='name',
        ),
    ]
